### ISSUE TITLE
models.pointnet

### ISSUE THREAD

**Issue by lizhi3158** [gabrieletiboni/paintnet#3]
ModuleNotFoundError: No module named 'models.pointnet'

**Comment by gabrieletiboni** [comment]
Thank you for your comment.

I believe pointnet is no longer officially supported, as I soon started using pointnet++ instead (https://arxiv.org/abs/1706.02413) which should generally have greater expressive power.

Simply call your scripts using `--backbone pointnet2` to switch from pointnet to pointnet++.

**Comment by gabrieletiboni** [comment]
@lizhi3158 I just noticed there was a leaking import error like you said, regardless of whether you call the script using pointnet2.

I just removed the import and pushed the code.
Let me know if it works now and I'll close the issue :)

**Comment by gabrieletiboni** [comment]
The fix should've solved the error, I'm closing the issue :)
